chore: Docker Hub 로그인 성공 여부 디버깅 추가

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -36,12 +36,23 @@ jobs:
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
+      - name: Log in to Docker Hub
+        run: |
+          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+          if docker info | grep -q "Username"; then
+            echo "Docker login successful"
+          else
+            echo "Docker login failed"
+            exit 1
+          fi
+
       - name: Build and Push Docker Image
         run: |
           docker build --build-arg JAR_FILE=build/libs/Backend-0.0.1-SNAPSHOT.jar -t deepdive/i-contact-backend:latest .
           docker tag deepdive/i-contact-backend:latest deepdive/i-contact-backend:${{ github.sha }}
           docker push deepdive/i-contact-backend:latest
           docker push deepdive/i-contact-backend:${{ github.sha }}
+  
 
   deploy:
     runs-on: ubuntu-latest
